# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokeamount', to='poke.Friend')),
                ('poking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poketake', to='poke.Friend')),
            ],
        ),
    ]
