# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='dob',
        ),
    ]
